version: "3"

services:
  mongo_db:
    image: mongo:latest
    container_name: db_container
    restart: always
    volumes:
      - mongo_db:/data/db
    # ports:
    #   - "27017:27017"

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000" # Backend port
    environment:
      MONGODB_URI: mongodb://mongo_db:27017/
      PORT: 8000
      JWT_SECRET: seckret

    depends_on:
      - mongo_db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80" # Frontend port 8080 mapped to container's port 80

volumes:
  mongo_db: {}
